### ISSUE TITLE
Missing "assembly/{refgenome}_full.fa"

### ISSUE THREAD

**Issue by yassineS** [AnimalGenomicsETH/bovine-graphs#3]
Thank you for sharing your code!

I am taking the snakemake pipeline for a spin, and it is not obvious what the "assembly/{refgenome}_full.fa" supposed to be. From scanning the code briefly, I thought this would be something created by the "sv" subworkflow, however, the `mash sketch` command fails in the dry run because it can't find the "assembly/{refgenome}_full.fa" file.

Thanks again!

**Comment by danangcrysnanto** [comment]
Hi this file is used later for transcriptome and WGS mapping that I appended the SV into these full reference genome. You can just create this file with `touch assembly/UCD.fa` if you work with cattle and the SV part will run

**Comment by yassineS** [comment]
Thank you for the quick reply, but that didn't help the case:

```
$ snakemake -j 8 -s ../tools_and_scripts/bovine-graphs/snake_graph.py
localrules directive specifies rules that are not present in the Snakefile:
	analyze_gene_model
	create_extended_ref
	merge_expression

Building DAG of jobs...
MissingInputException in line 171 of /localscratch/ysouilmi/dog_genome_graph/tools_and_scripts/bovine-graphs/subworkflows/sv_analysis.py:
Missing input files for rule create_full_ref:
assembly/canFam3_full.fa

$ tree workdir/assembly/
workdir/assembly/
├── basenji1.fa
├── basenji2.fa
├── canFam3.fa
├── canFam4.fa
├── canFam5.fa
├── canFam6.fa
├── dhole.fa
├── dingo_cooinda.fa
├── dingo_sandy.fa
├── wolf1.fa
└── wolf2.fa

0 directories, 11 files
```

And here's the content of the config file:
```
$ cat config/config.yaml
workdir: /localscratch/ysouilmi/dog_genome_graph/minigraph_pipeline/workdir

# Setting for SV analysis
# gff always relative to the workdir

gffinput: refs/canFam3.ensGene.gff

# Setting for rna-seq analysis
rna_seq: False
reference: canFam3

# diamond protein db for blast
refprot:  /localscratch/ysouilmi/dog_genome_graph/minigraph_pipeline/workdir/refs/diamond.db
rna_basedir: /localscratch/ysouilmi/dog_genome_graph/minigraph_pipeline/workdir/rnaseq_data
rna_anims:
  - SRR7334235_RNASeq_of_dingo_adult_female_ovary
  - SRR7334236_RNASeq_of_dingo_adult_female_blood
  - SRR7334234_RNASeq_of_dingo_adult_female_muscle


# setting for wgs analysis
dna_seq: False
```

I tried running that with `rna_seq` set to False and True.

**Comment by danangcrysnanto** [comment]
Hi based on the log file, it is caused by 
```
Missing input files for rule create_full_ref:
assembly/canFam3_full.fa
```

So you should provide it, as I mentioned you can have the dummy one if you do not yet want to have the RNA analysis with `touch assembly/canFam3_full.fa` and provide full reference genome of canFam3_full.fa (including unplaced contig) in the `assembly` folder with the name of `canFam3_full.fa`. 

Hope this helps.

**Comment by yassineS** [comment]
So if I understand correctly, `assembly/{refgenome}.fa` is the primary assembly with only the main contigs (chromosomes), and `assembly/{refgenome}_full.fa` is the full assembly with the unplaced contigs and any additional alt/decoy contigs?

**Comment by danangcrysnanto** [comment]
Hi 

Yes that's correct, in our pipeline we only construct graphs from autosomes, but we combined the non-ref sequences with the full genome for the transcriptomic and variant analysis. I suggest to read [our paper](https://www.pnas.org/doi/10.1073/pnas.2101056118) for further details

**Comment by yassineS** [comment]
thanks a lot!
